### ISSUE TITLE
Pointer input

### ISSUE THREAD

**Issue by ammen99** [marcof-nikogo/wf-external-decoration#1]
I briefly looked through the Readme and the Wayfire plugin implementation and I'm wondering why you decided to handle resize and move and close and maximize etc. requests on the Wayfire side? You could for example let pointer and touch events go to the client, then it emits a move/resize request if needed, and your plugin receives then the move/resize requests on the decoration toplevel and creates move/resize requests on the Wayfire side?

This would have the benefit that the client can do animation on hover, place buttons wherever it wants, etc.

**Comment by marcof-nikogo** [comment]
Well, simply put, at the time I didn't know how to handle a move/resize directly on the plugin side responding to a request...
But I'll give a try. 
The preligth of buttons already works, the rendering engine handle this.
Do you have any suggestion on how to handle the shade in a less barbaric way as it is now ?

**Comment by ammen99** [comment]
> Well, simply put, at the time I didn't know how to handle a move/resize directly on the plugin side responding to a request...
> But I'll give a try.

You need to connect to the move/resize/maximize/etc wlroots signals on this toplevel object https://github.com/marcof-nikogo/wf-external-decoration/blob/main/wf-plugin/wf-external-decor.cpp#L644 - that would be requests coming from the decoration

And you turn them to move/resize/tile/etc requests for the actual view: https://github.com/WayfireWM/wayfire/blob/master/src/api/wayfire/window-manager.hpp#L38

> Do you have any suggestion on how to handle the shade in a less barbaric way as it is now ?

You shouldn't need to remove the nodes of the view. Instead, you can simply walk the list of children and disable all children which are not the decoration node itself - this is the "idiomatic" way to exclude these nodes from rendering and input handling, which ought to be enough in this case afaik.

EDIT: by walk I mean just iterating over the children list, no need for recursion or anything since disabling a node also disables all of its children.

**Comment by marcof-nikogo** [comment]
Thanks... I'm moving the pointer events handling on the client size.
Regarding the shade I tried to only disable the node, but it is re enabled in many cases, depending on the app. A damned one is smplayer with systray enabled, but others too manage to re enabling it.

**Comment by ammen99** [comment]
> A damned one is smplayer with systray enabled, but others too manage to re enabling it.

In which cases exactly are they re-enabled? Do you hide-to-tray and show again? Some apps do that by unmapping themselves and mapping again - so maybe you need to un-shade on unmap (so that you don't double-disable a node, enable/disable is 'refcounted') and then re-shade on map?

**Comment by marcof-nikogo** [comment]
Yeah, it unmap and remap, and the view id doesn't change. 
But there are other cases the node is re enabled, with other apps.
I'll see if I can remember which ones...

**Comment by marcof-nikogo** [comment]
Well, it it is not possible to move/resize a window client side, even when the windows is not grabbed by the plugin. They cannot know their position too.
It is a limitation of wayland, clients have not initiative at all.

**Comment by ammen99** [comment]
Move and resize work in a different way. When the client wants to resize, it sends a request to the compositor, and the compositor then fulfills the request. It is kind of separation of concerns: the client tracks where the resize/dragging areas are, and the compositor implements the actual moving.

**Comment by ammen99** [comment]
Also forgot to mention, by default gtk3 windows will emit this signal on their own when you drag the titlebar. I am not sure how your decorator client works with this, but since it is gtk3 based (afaik) probably gtk will just do the right thing and send these events to the compositor? And then the plugin can pick them up. I could try to make a patch tomorrow if you cannot figure it out, it ought to be simple ..

**Comment by marcof-nikogo** [comment]
I connected to the move request on the plugin side, and on the client called gtk_window_move responding to a click on the frame.
But no event came...
I did already know that on wayland a program can not move a window, at least not on gtk3. But connecting to the move request seemed a way to get there.
Unfortunately doesn't work, or I'm missing something.
When I adapted my desktop to wayland it was a set back, some applets show a window, but there was not a way to get them positioned. The workaround was to use gtk-layer-shell. On the desktop it makes sense, but doesn't seem a good solution for the decorations.

> by default gtk3 windows will emit this signal on their own when you drag the titlebar

If it is the client decoration top bar, a thing used a lot by the gtk and gnome crew, may be. But if you use it the window turns out not decorable. You find it in the GtkFilechooserDialog, or in Devhelp and D-Spy.  

But all I  have is the naked window under/around the decorated view.

**Comment by ammen99** [comment]
> I connected to the move request on the plugin side, and on the client called gtk_window_move responding to a click on the frame.

gtk_window_move is used for one-off movement and doesn't work in Wayland. The correct call is this thing here: https://docs.gtk.org/gdk4/method.Toplevel.begin_move.html (found it for gdk4, but I assume a similar thing should exist for gdk3). Same for resize as well.

EDIT: for gtk/gdk3, https://docs.gtk.org/gtk3/method.Window.begin_move_drag.html

**Comment by marcof-nikogo** [comment]
It works ! 
Tomorrow I'll handle resize and the buttons. Now I'm dreaming my bed...
Many thanks !

**Comment by marcof-nikogo** [comment]
I reworked the move, resize and button handling on the client side.
What triggers the request_show_window_menu event ?
Now that there are pointer events on the client I tried again to popup a menu but to no avail...

**Comment by ammen99** [comment]
According to google https://docs.gtk.org/gdk3/method.Window.show_window_menu.html
