### ISSUE TITLE
Marco themes improperly scaled on hidpi monitor

### ISSUE THREAD

**Issue by lukefromdc** [marcof-nikogo/wf-external-decoration#5]
On a 4K display and a scaling factor of 2.0, using Debian's libwlroots12_0.17.1-2_amd64.deb and wayfire_0.8.0+git20240110-1_amd64.deb on Debian Unstable in a mate-wayfire session, all marco themes tested render oversize, appearing to be doubly scaled thus showing huge and blurry buttons. Setting the font size (which is supposed to determine button size) seems to be entirely ignored.

For my current testing, I was able to work around this by scaling down my normal metacity theme and renaming it. Buttons are still blurry (even from hi-res .svg files) but I was able to get them to their expected size this way

**Comment by marcof-nikogo** [comment]
I think this can be solved using the scale factor when setting  pango fonts.  Firedecor does so.
After easter I'll be on holyday, hope to have time to address these issues.

**Comment by lukefromdc** [comment]
After applying https://github.com/marcof-nikogo/wf-external-decoration/pull/7 and setting my normal font size, I now get the correct decoration size. I actually wound up using a micrometer to measure buttons in both Menta and my own UbuntuStudio theme, and got an exact match to the x11 button sizes. I think this one can now be closed, feel free to reopen it if anyone else gets this with the font reading fixed.

Also note that I am now using the same font (sans 9) in x11 and wayfire and getting the same results. Lots of things in wayland seem to be taken care of by the compositor instead of having scaling handled in each program. This makes maintainance easier but does have the disadvantage of making it harder to get good fractional scaling (as mentioned in other places). At any rate, that design decision is out of our hands.
